### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by hoangvn79** [rkapl123/DBAddin#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	BC2001	file 'H:\DBAddin-master\DBAddin-master\source\My Project\AssemblyInfo.vb' could not be found	DBaddin	H:\DBAddin-master\DBAddin-master\source\vbc	1	Active
Please 01 releases!

**Comment by rkapl123** [comment]
Hi hoangvn79!
Sorry that I didn't mention it earlier, the whole project is still work in progress, I've not finished yet the migration from VB6 to VB.Net completely. So even though the solution should build, it won't work properly.

**Comment by hoangvn79** [comment]
Thanks you reply!
Your project is very good! But i can't do your project, I want do with
your project, your project

2019-03-11 4:53 GMT+07:00, Roland Kapl <notifications@github.com>:

**Comment by rkapl123** [comment]
added the missing AssemblyInfo.vb
