### ISSUE TITLE
How to use the function DBSetQueryPivot without error???

### ISSUE THREAD

**Issue by hoangvn79** [rkapl123/DBAddin#11]
**When I use Shortcut to fill the function DBSetQueryPivot  in the cell as shown in the images below:**

![1](https://github.com/rkapl123/DBAddin/assets/35492809/73a15723-dfa9-4bf5-b234-201f377cfae4)

**After left-click on the function DBSetQueryPivot  , I get the following errors in turn:**
![2](https://github.com/rkapl123/DBAddin/assets/35492809/958321d5-817f-468c-b28b-13d361546f20)
![3](https://github.com/rkapl123/DBAddin/assets/35492809/cfe24db5-73e3-4c73-986f-c707ecb7d836)
![4](https://github.com/rkapl123/DBAddin/assets/35492809/eb2af754-6a8b-4a62-91e7-f7ebca07d222)

**Then enter the SQL and Connecting in the function DBSetQueryPivot  , the error is as follows:**
![5](https://github.com/rkapl123/DBAddin/assets/35492809/82e50d80-e598-4dd0-9ba3-70c1ecf7c378)

So what should I do to not get the above function error?

**Comment by rkapl123** [comment]
Which version of excel do you use?

**Comment by hoangvn79** [comment]
Hi, I use Excel 2019 but when I change ExcelVersionForPivot, it doesn't get error in image 2 but error from image 3, 4,5 because  error row: pivotTables.Add(PivotCache:=pivotcache, TableDestination:=TargetCell.Offset(1, 0), DefaultVersion:=ExcelVersionForPivot).

**Comment by rkapl123** [comment]
OK, there is a problem with the initial select statement I have to use to create a xlCmdSql type pivot table (actually the cache, which is assigned to the table later). This was `select CURRENT_TIMESTAMP`, I have changed that to an even more general `select 1` + additionally it's customizable with the new setting `pivotTableCmdTextToSet + env` (+ env should be replaced with the number of your environment, e.g. `pivotTableCmdTextToSet1`).
Another source of errors might be the connection string, I'm using `<add key="ConstConnString5" value="Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\dev\DBAddin.NET\test\pubs.mdb;;Persist Security Info=False;"/>`.
This is being replaced with the OLEDB driver connection string by adding 'OLEDB;" in front of it, however you can configure a direct connection string for this by setting `<add key="AltConnString5" value="whatever works for you ..."/>`.
I'm going to push version 1.0.0.50 soon, there is also more exception handling code to get more details on any problems here.

**Comment by rkapl123** [comment]
I've pushed 1.0.0.50 now, you just have to set `<add key="useAltDBListFetch" value="true" />` to false again, I started to migrate the ADODB dependent code to ADO.Net now (and this is the switch to use the new code).

**Comment by hoangvn79** [comment]
Thanks!
