### ISSUE TITLE
error: DBListFetch no show function in excel

### ISSUE THREAD

**Issue by hoangvn79** [rkapl123/DBAddin#3]
Hii!
I tried compiling debug to run in excel but did not see DBListFetch function appear. I don't know where the error is

**Comment by rkapl123** [comment]
Hi, as I mentioned in #2, there is no working codebase here.
If you need the Addin, please refer to https://sourceforge.net/projects/dbaddin/
-regards,
Roland

**Comment by rkapl123** [comment]
However, be aware that the old DB-Addin only works for 32bit Office installations.
