### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by hoangvn79** [rkapl123/DBAddin#4]
I try to use the DBListFetch function specifically as follows:
In Cell A3: =DBListFetch (B3; activeConnString; A4; G4: H4; 1) 
with  name activeConnString = provider=Microsoft.Jet.OLEDB.4.0;Data Source="H:\DBADDIN\pubs.MDB"
then error:
Env:, Error (Object reference not set to an instance of an object.) in DBListFetch, callID : [DBFuncsTest (version 1).xlsx]example5!$A$3
I don't know why ???
In dbaddin when in VB6 it is not the same

**Comment by rkapl123** [comment]
Because it’s not ready yet. Please wait for the first release, I’ll mention the functionality that can be tested then.

Regards
Roland
