### ISSUE TITLE
why error when convert class Mapper to Module Mapper?

### ISSUE THREAD

**Issue by hoangvn79** [rkapl123/DBAddin#7]
![2019-06-08_04-55-06](https://user-images.githubusercontent.com/35492809/59135612-da82e300-89a9-11e9-9e37-7a185d80ca08.png)
Hi, when i run debug after convert class Mapper to Module Mapper is error.

**Comment by rkapl123** [comment]
Hi, the Mapper concept has been completely redone, the current implementation is using a zero-code approach, so there is no need to create VBA Macros anymore.
You might check the latest commit, I've also added a creation mechanism for DBMappers.
-regards,
Roland
